Rasa process starting
Rasa process starting
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Circuit breaker tripped. Stopped predicting more actions for sender 'default'
Circuit breaker tripped. Stopped predicting more actions for sender 'default'
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_details'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_details'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'get_product_price'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
HTTPConnectionPool(host='localhost', port=5055): Read timed out. (read timeout=300)
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=5055): Read timed out. (read timeout=300)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 312, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/utils.py", line 641, in request
    **kwargs)
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=5055): Read timed out. (read timeout=300)
Encountered an exception while running action 'get_product_price'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
HTTPConnectionPool(host='localhost', port=5055): Read timed out. (read timeout=300)
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/neckai/BOT/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=5055): Read timed out. (read timeout=300)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 312, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/utils.py", line 641, in request
    **kwargs)
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=5055): Read timed out. (read timeout=300)
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_price'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_price'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_price'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_price'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'get_product_price' set a slot type 'price' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"price": 1828}' after the action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_price'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_price'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_color'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_color'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_price'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_price'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'get_product_storage'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_storage'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_price'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_price'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_storage'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_storage'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_storage'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_storage'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'get_product_price'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'get_product_price'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'confirm_buy'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'confirm_buy'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'confirm_buy'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'confirm_buy'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'forward_complain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'forward_complain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'forward_complain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'forward_complain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'forward_complain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'forward_complain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'forward_complain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
1 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    1
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 1 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    1
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    2
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 2 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    2
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
3 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    3
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 3 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    3
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
4 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    4
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 4 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    4
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'forward_complain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/neckai/BOT/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
5 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    5
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 5 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    5
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
9 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    9
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 9 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    9
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
11 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    11
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 11 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    11
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/bot/intent_classifier_tensorflow_embedding.ckpt
/home/neckai/BOT/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
22 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    22
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 22 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    22
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
23 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    23
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 23 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    23
Encountered an exception while running action 'forward_complain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
24 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    24
Traceback (most recent call last):
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 316, in run
    self._validate_action_result(response_data)
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 259, in _validate_action_result
    raise e
  File "/home/neckai/BOT/lib/python3.6/site-packages/rasa_core/actions/action.py", line 251, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/neckai/BOT/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 24 is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions.html

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    24
